language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999

install:
# - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -Scope LocalMachine -ExecutionPolicy Bypass'; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PowerShell -Command 'Set-ExecutionPolicy -ExecutionPolicy RemoteSigned'; fi

after_script:
  - julia -e 'using Pkg, MatrixPerspective; cd(joinpath(dirname(pathof(MatrixPerspective)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly    
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using MatrixPerspective; include(joinpath(dirname(pathof(MatrixPerspective)), "..", "docs", "make.jl"))'
      after_script: skip
      after_success: skip  
      
